Feature newpull request
kinginthenorthcodez/Portifolio-website-north pull request #4
Opened 2022-01-11 21:53 UTC by kinginthenorthcodez

latest pull request for contact form changes

2022-01-11 22:34 UTC, micheaol requested changes
Hi @kinginthenorthcodez 🥇 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 


## Required Changes ♻️
- _Check the comments under the review._
- Please ensure you customize the README.md file to your project

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-11 22:34 UTC, micheaol commented on index.html
> -           <button type="button" class="btn-form">Get in touch</button>
Please ensure that the form is submitted successfully after clicking the submit `<button>`. Please check the `<button>` `type`, you might want to change it from `<button>` to `<submit>` I think this is the reason the APP is not performing as expected.

2022-01-11 22:34 UTC, micheaol commented on index.html
> +        <textarea name="textarea" id="message" placeholder="Enter your message here" maxlength="500" rows="5" required>Enter your message here
Please ensure you stick to the design templates in Figma as much as possible, this includes the font, colors, images, and spacing (margin/padding).

## Your design: 
![your-design](https://user-images.githubusercontent.com/10332499/149031640-e518aefa-1c0e-474a-bdf8-83df1c14403e.PNG)

## Figma design:
![figma](https://user-images.githubusercontent.com/10332499/149031679-ea3e76d7-9e15-4c26-b2ca-43a31dc61146.PNG)

2022-01-12 01:32 UTC, kinginthenorthcodez commented on index.html
> +        <textarea name="textarea" id="message" placeholder="Enter your message here" maxlength="500" rows="5" required>Enter your message here
made changes as per review for the margins and fonts

2022-01-12 01:33 UTC, kinginthenorthcodez commented
Updated changes as required 👍🏽

2022-01-12 01:42 UTC, rotimiazeez approved these changes
# Hi Team👏, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🎉
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 16:38 UTC, kinginthenorthcodez commented
> # Hi Team👏,
> ### Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 🎉
> Congratulations! 🎉
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hi @rotimiazeez  i see in the dashboard it still showing submit, thanks for the reviews.

2022-01-12 21:34 UTC, merged