Added-Feature-desktop-version
kinginthenorthcodez/Portifolio-website-north pull request #6
Opened 2022-01-15 16:56 UTC by kinginthenorthcodez

#Features
-Added navigations links
-Added media queries for responsive layout

2022-01-15 18:24 UTC, Whoistolu requested changes
Hi @kinginthenorthcodez ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

#### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-15 18:24 UTC, Whoistolu commented on assets/css/style.css
> +  }
- [ ] [REQUIRED] Kindly ensure that the content of your form-container class has equal margins on the right and left. Right now the right margin on your form is much than the left margin. Please check the figma template to get the exact margins.

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
![3](https://user-images.githubusercontent.com/58692590/149632686-ec9f7324-2a67-44c5-b5fd-7335540ae458.png) | ![33](https://user-images.githubusercontent.com/58692590/149632693-b602baa7-9346-4d40-b63a-bb93069fe1b6.png)

2022-01-15 18:24 UTC, Whoistolu commented on assets/css/style.css
> +  }
- [ ] [REQUIRED] Kindly ensure that you stick to the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468) as much as possible (font, font-size, margin, padding, color).

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
![5](https://user-images.githubusercontent.com/58692590/149633016-fa5c37de-7bdf-48d4-9ef7-16416b71b07b.png) | ![55](https://user-images.githubusercontent.com/58692590/149633025-d3f9b77c-7812-4836-8a74-adde64c60896.png)

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
![6](https://user-images.githubusercontent.com/58692590/149633265-52c56588-86b4-4186-abfb-250824081347.png) | ![66](https://user-images.githubusercontent.com/58692590/149633207-5d916fcd-a0aa-4f76-92ad-846e869aed01.png)

2022-01-16 03:08 UTC, kinginthenorthcodez commented on assets/css/style.css
> +  }
Updated fixes for the desktop design

2022-01-16 03:08 UTC, kinginthenorthcodez commented on assets/css/style.css
> +  }
fixed errors

2022-01-16 03:08 UTC, kinginthenorthcodez commented on assets/css/style.css
> +  }
Fixed about me section 👍🏽

2022-01-16 03:08 UTC, kinginthenorthcodez commented on assets/css/style.css
>    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
changes made according to the review 👍🏽

2022-01-16 03:31 UTC, alexander16108 approved these changes
Hi @kinginthenorthcodez, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-16 04:11 UTC, merged